language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
# There's no nicer way to specify this matrix; see
# https://github.com/travis-ci/travis-ci/issues/1519.
matrix:
  include:
    - jdk: openjdk6
      scala: 2.10.5
      env: TEST_HADOOP_VERSION="1.0.4" TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk6
      scala: 2.10.5
      env: TEST_HADOOP_VERSION="1.2.1" TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk6
      scala: 2.10.5
      env: TEST_HADOOP_VERSION="2.2.0" TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_HADOOP_VERSION="2.2.0" TEST_SPARK_VERSION="1.4.1"
    # Scala 2.11 tests:
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_HADOOP_VERSION="2.2.0" TEST_SPARK_VERSION="1.4.1"
script:
  - sbt -Dhadoop.testVersion=$TEST_HADOOP_VERSION -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
